### ISSUE TITLE
how to Integrate Deeplink  info QR 

### ISSUE THREAD

**Issue by kietle2000** [dagronf/QRCode#39]

**Comment by dagronf** [comment]
Hi there,

Deeplink relates to the content of the QR code rather than the actual QR code generation.  Once you have a deep link URL that works with your app, you can use this library to generate a QR code containing the link.

Here are some web pages that discuss deep linking (using both universal links and url schemes)

• https://developer.apple.com/ios/universal-links/
• https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app
• https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content
• https://medium.com/wolox/ios-deep-linking-url-scheme-vs-universal-links-50abd3802f97
• https://www.branch.io/resources/blog/how-to-setup-universal-links-to-deep-link-on-apple-ios/
• https://www.donnywals.com/handling-deeplinks-in-your-app/

Have a misunderstood your issue?

**Comment by dagronf** [comment]
Closing due to lack of feedback
